apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 80        # 외부 접근 포트
      targetPort: 8501 # 컨테이너 내부 Streamlit 포트